class MyLocators:

    name_Username = "userName"
    link_Text_Home = "Home"
    link_Text_Register = "Register here"
    link_Text_Flights = "Flights"

    # Register
    name_FirstName = "firstName"
    name_LastName = "lastName"
    name_Phone = "phone"
    name_Email = "userName"
    name_Address = "address1"
    name_City = "city"
    name_State = "state"
    name_PostalCode = "postalCode"
    name_Country = "country"
    id_Email = "email"
    name_Password = "password"
    name_ConfirmPassword = "confirmPassword"
    name_Submit = "submit"
    xpath_message = "/html/body/div[2]/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[3]/td/p[2]/font"

    # Flights
    name_TripType = "tripType"
    xpath_RoundTripe = "/html/body/div[2]/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[2]/td[2]/b/font/input[1]"
    xpath_OneWay = "/html/body/div[2]/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[2]/td[2]/b/font/input[2]"
    name_Passengers = "passCount"
    name_Departing_From = "fromPort"
    name_From_Month = "fromMonth"
    name_From_Day = "fromDay"
    name_Arriving = "toPort"
    name_Returning_Month = "toMonth"
    name_Returning_Day = "toDay"
    xpath_Economy_Class = "/html/body/div[2]/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[9]/td[2]/font/input"
    xpath_Business_Class = "/html/body/div[2]/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[9]/td[2]/font/font/input[1]"
    xpath_First_Class = "/html/body/div[2]/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[9]/td[2]/font/font/input[2]"
    name_Airline = "airline"
    name_Continue = "findFlights"
    xpath_message_2 = "/html/body/div[2]/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr[1]/td[2]/table/tbody/tr[1]/td/p/font/b/font[1]"